dist: trusty
language: node_js
node_js:
  - "12"
install:
  - yarn
sudo: false
branches:
  only:
    - master
notifications:
  email:
    on_success: change
    on_failure: always
cache: yarn
script:
  - yarn build
  - cat coverage/lcov.info | node_modules/.bin/coveralls || echo "Coveralls upload failed"
